# Define a porta do servidor Java (8080 é o padrão)
server.port=8081

# Configurações do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:minixsigdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Habilita o console do H2 no navegador (Para você ver o banco visualmente)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Faz o Hibernate (JPA) criar as tabelas automaticamente baseado nas suas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true